spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

